[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = test_*.py *_test.py tests.py
testpaths = scanner/tests
norecursedirs =
    .git
    .venv
    slither
    venv-slither
    venv-mythril