from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable
from uuid import UUID

from scanner.domain.enums import (
    RecommendationPriority,
    RemediationEffort,
    RiskCategory,
    RuleType,
    Severity,
)
from scanner.domain.exceptions import DomainValidationError
from scanner.domain.value_objects import RecommendationTemplate


@dataclass(
    frozen=True,
    slots=True,
)
class Recommendation:
    """
    Immutable Value Object representing a runtime remediation recommendation.

    A Recommendation is generated by applying a RecommendationTemplate to
    one or more findings during a scan. It encapsulates remediation guidance,
    traceability to source findings, and contextual metadata.
    """

    rule_type: RuleType
    template_identifier: str

    title: str
    description: str
    remediation: str

    priority: RecommendationPriority
    effort: RemediationEffort

    affected_finding_ids: tuple[str | UUID, ...]

    cwe: str | None = None
    swc: str | None = None
    owasp: str | None = None

    references: tuple[str, ...] = ()
    tags: tuple[str, ...] = ()

    requires_manual_review: bool = False
    estimated_fix_hours: float | None = None
    automation_available: bool = False

    def __post_init__(self) -> None:
        """
        Validate and normalize Recommendation domain invariants.
        """
        if not isinstance(self.rule_type, RuleType):
            raise DomainValidationError(
                "rule_type must be a valid RuleType."
            )

        object.__setattr__(
            self,
            "template_identifier",
            self._normalize_required_string(self.template_identifier, "template_identifier"),
        )
        object.__setattr__(
            self,
            "title",
            self._normalize_required_string(self.title, "title"),
        )
        object.__setattr__(
            self,
            "description",
            self._normalize_required_string(self.description, "description"),
        )
        object.__setattr__(
            self,
            "remediation",
            self._normalize_required_string(self.remediation, "remediation"),
        )

        if not isinstance(self.priority, RecommendationPriority):
            raise DomainValidationError(
                "priority must be RecommendationPriority."
            )

        if not isinstance(self.effort, RemediationEffort):
            raise DomainValidationError(
                "effort must be RemediationEffort."
            )

        if not isinstance(self.requires_manual_review, bool):
            raise DomainValidationError(
                "requires_manual_review must be boolean."
            )

        if not isinstance(self.automation_available, bool):
            raise DomainValidationError(
                "automation_available must be boolean."
            )

        # Disallow strings or bytes directly passed as iterable collections
        if isinstance(self.affected_finding_ids, (str, bytes)):
            raise DomainValidationError(
                "affected_finding_ids must be an iterable of identifiers, not a string."
            )

        try:
            finding_ids = tuple(self.affected_finding_ids)
        except TypeError as exc:
            raise DomainValidationError(
                "affected_finding_ids must be an iterable collection."
            ) from exc

        for finding_id in finding_ids:
            if not finding_id or (
                isinstance(finding_id, str) and not finding_id.strip()
            ):
                raise DomainValidationError(
                    "affected_finding_ids must contain non-empty identifiers."
                )

        # Preserve order while deduplicating
        deduped_finding_ids = tuple(dict.fromkeys(finding_ids))

        if not deduped_finding_ids:
            raise DomainValidationError(
                "Recommendation must reference at least one finding."
            )

        object.__setattr__(self, "affected_finding_ids", deduped_finding_ids)

        # Optional security standard identifiers
        object.__setattr__(
            self, "cwe", self._normalize_optional_identifier(self.cwe, "cwe")
        )
        object.__setattr__(
            self, "swc", self._normalize_optional_identifier(self.swc, "swc")
        )
        object.__setattr__(
            self, "owasp", self._normalize_optional_identifier(self.owasp, "owasp")
        )

        # Normalize reference URLs/strings
        normalized_references = self._normalize_string_sequence(
            self.references, "references"
        )
        object.__setattr__(self, "references", normalized_references)

        # Normalize tag strings
        normalized_tags = self._normalize_string_sequence(self.tags, "tags")
        object.__setattr__(self, "tags", normalized_tags)

        if self.estimated_fix_hours is not None and (
            not isinstance(self.estimated_fix_hours, (int, float))
            or self.estimated_fix_hours < 0
        ):
            raise DomainValidationError(
                "estimated_fix_hours must be a non-negative number."
            )

    @classmethod
    def from_template(
        cls,
        template: RecommendationTemplate,
        rule_type: RuleType,
        finding_ids: Iterable[str | UUID],
    ) -> Recommendation:
        """
        Factory method constructing a Recommendation runtime object from a template
        and associated finding identifiers.
        """
        if not isinstance(template, RecommendationTemplate):
            raise DomainValidationError(
                "template must be RecommendationTemplate."
            )

        if not isinstance(rule_type, RuleType):
            raise DomainValidationError(
                "rule_type must be RuleType."
            )

        return cls(
            rule_type=rule_type,
            template_identifier=template.identifier,
            title=template.title,
            description=template.description,
            remediation=template.remediation,
            priority=template.priority,
            effort=template.effort,
            affected_finding_ids=tuple(finding_ids),
            cwe=template.cwe,
            swc=template.swc,
            owasp=template.owasp,
            references=template.references,
            tags=template.tags,
            requires_manual_review=template.requires_manual_review,
            estimated_fix_hours=template.estimated_fix_hours,
            automation_available=template.automation_available,
        )

    def merge(self, other: Recommendation) -> Recommendation:
        """
        Combines this recommendation with another recommendation having the same identity key.

        Aggregates and deduplicates affected finding IDs while keeping the underlying
        remediation template metadata identical.
        """
        if not isinstance(other, Recommendation):
            raise DomainValidationError("Can only merge with another Recommendation instance.")

        if self.key != other.key:
            raise DomainValidationError(
                f"Cannot merge recommendations with mismatched keys: {self.key} vs {other.key}"
            )

        combined_finding_ids = self.affected_finding_ids + other.affected_finding_ids

        return Recommendation(
            rule_type=self.rule_type,
            template_identifier=self.template_identifier,
            title=self.title,
            description=self.description,
            remediation=self.remediation,
            priority=self.priority,
            effort=self.effort,
            affected_finding_ids=combined_finding_ids,
            cwe=self.cwe,
            swc=self.swc,
            owasp=self.owasp,
            references=self.references,
            tags=self.tags,
            requires_manual_review=self.requires_manual_review,
            estimated_fix_hours=self.estimated_fix_hours,
            automation_available=self.automation_available,
        )

    # ==========================================================
    # Static Normalization Helpers
    # ==========================================================

    @staticmethod
    def _normalize_required_string(value: str, field_name: str) -> str:
        """Validates that a required value is a non-empty string and returns it stripped."""
        if not isinstance(value, str):
            raise DomainValidationError(f"{field_name} must be a string.")

        stripped = value.strip()
        if not stripped:
            raise DomainValidationError(f"{field_name} cannot be blank.")

        return stripped

    @staticmethod
    def _normalize_optional_identifier(value: str | None, field_name: str) -> str | None:
        """Validates an optional string identifier, returning None for blank inputs."""
        if value is None:
            return None

        if not isinstance(value, str):
            raise DomainValidationError(
                f"{field_name} must be a string or None."
            )

        stripped = value.strip()
        return stripped if stripped else None

    @staticmethod
    def _normalize_string_sequence(
        sequence: Any, field_name: str
    ) -> tuple[str, ...]:
        """Validates and standardizes any iterable of strings into a tuple of stripped values."""
        if isinstance(sequence, (str, bytes)):
            raise DomainValidationError(
                f"{field_name} must be an iterable collection, not a string."
            )

        try:
            iterator = iter(sequence)
        except TypeError as exc:
            raise DomainValidationError(
                f"{field_name} must be an iterable sequence."
            ) from exc

        normalized_items: list[str] = []
        for item in iterator:
            if not isinstance(item, str):
                raise DomainValidationError(
                    f"{field_name} elements must be strings."
                )

            stripped = item.strip()
            if not stripped:
                raise DomainValidationError(
                    f"{field_name} elements cannot be blank."
                )
            normalized_items.append(stripped)

        return tuple(dict.fromkeys(normalized_items))

    # ==========================================================
    # Derived Properties & Domain Helpers
    # ==========================================================

    @property
    def key(self) -> tuple[RuleType, str]:
        """Hashable composite key for grouping/merging recommendations."""
        return self.rule_type, self.template_identifier

    @property
    def severity(self) -> Severity:
        """Exposes default severity directly from rule_type."""
        return self.rule_type.default_severity

    @property
    def risk_category(self) -> RiskCategory:
        """Exposes risk category directly from rule_type."""
        return self.rule_type.risk_category

    @property
    def primary_reference(self) -> str | None:
        """Returns the primary reference URL if available."""
        return self.references[0] if self.references else None

    @property
    def affected_finding_count(self) -> int:
        """Returns the number of distinct findings associated with this recommendation."""
        return len(self.affected_finding_ids)

    @property
    def affects_multiple_findings(self) -> bool:
        """Returns True if this recommendation aggregates multiple findings."""
        return self.affected_finding_count > 1

    @property
    def has_cwe(self) -> bool:
        return self.cwe is not None

    @property
    def has_swc(self) -> bool:
        return self.swc is not None

    @property
    def has_owasp(self) -> bool:
        return self.owasp is not None

    @property
    def has_references(self) -> bool:
        return bool(self.references)

    @property
    def has_tags(self) -> bool:
        return bool(self.tags)

    @property
    def standards(self) -> tuple[str, ...]:
        """Returns all mapped security standard IDs."""
        return tuple(
            val
            for val in (self.cwe, self.swc, self.owasp)
            if val is not None
        )

    @property
    def is_immediate(self) -> bool:
        """True if priority is high and requires rapid action."""
        return self.priority is RecommendationPriority.HIGH

    @property
    def is_automatable(self) -> bool:
        return self.automation_available

    @property
    def is_manual_only(self) -> bool:
        """True if fixing requires manual effort without automation options."""
        return self.requires_manual_review and not self.automation_available

    @property
    def estimated_days(self) -> float | None:
        """Converts estimated fix hours to standard 8-hour workdays, rounded to 2 decimals."""
        if self.estimated_fix_hours is None:
            return None
        return round(self.estimated_fix_hours / 8.0, 2)

    @property
    def is_quick_win(self) -> bool:
        """True if the remediation yields high security impact with low effort."""
        return (
            self.effort is RemediationEffort.LOW
            and self.priority is RecommendationPriority.HIGH
        )