# Generated by Django 5.2.12 on 2026-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('spoofing', 'Spoofing'), ('tampering', 'Tampering'), ('repudiation', 'Repudiation'), ('info_disclosure', 'Information Disclosure'), ('dos', 'Denial of Service'), ('elevation', 'Elevation of Privilege')], max_length=30)),
                ('description', models.TextField()),
                ('likelihood', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('impact', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('mitigation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-impact', '-likelihood'],
            },
        ),
    ]
