# Generated by Django 6.0.4 on 2026-04-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tool',
            field=models.CharField(choices=[('slither', 'Slither'), ('mythril', 'Mythril'), ('echidna', 'Echidna')], default='slither', max_length=20),
        ),
    ]
