# Generated by Django 6.0.4 on 2026-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('spoofing', 'Spoofing'), ('tampering', 'Tampering'), ('repudiation', 'Repudiation'), ('information_disclosure', 'Information Disclosure'), ('denial_of_service', 'Denial of Service'), ('elevation_of_privilege', 'Elevation of Privilege')], default='tampering', max_length=50)),
                ('likelihood', models.IntegerField(default=5)),
                ('impact', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('mitigation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
