# Generated by Django 5.2.12 on 2026-04-02 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('swc_id', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Finding Categories',
            },
        ),
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed'), ('executive', 'Executive')], max_length=20)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('html', 'HTML')], max_length=10)),
                ('content', models.BinaryField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SolidityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SuppressionBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['-severity', '-found_at']},
        ),
        migrations.AddField(
            model_name='finding',
            name='code_snippet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='confidence',
            field=models.IntegerField(default=100, help_text='Confidence 0-100'),
        ),
        migrations.AddField(
            model_name='finding',
            name='found_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Impact 0-10'),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finding',
            name='line_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='line_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='finding',
            name='reference_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='suppression_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='finding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='compilation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='compiled_abi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='compiled_bytecode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='critical_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='high_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='low_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='medium_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='source_code_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='total_findings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='swc_id',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('compiling', 'Compiling'), ('analyzing', 'Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('scan', 'swc_id', 'line_number', 'title')},
        ),
        migrations.AddField(
            model_name='finding',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.findingcategory'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['scan', '-severity'], name='scanner_fin_scan_id_effe32_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['swc_id'], name='scanner_fin_swc_id_6a579f_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status'], name='scanner_fin_status_b3eb6c_idx'),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanreport',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scanner.scanjob'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='solidity_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanner.solidityversion'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['-created_at', 'status'], name='scanner_sca_created_d04ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_1fc5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['source_code_hash'], name='scanner_sca_source__2542b8_idx'),
        ),
        migrations.AddField(
            model_name='suppressionbaseline',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.finding'),
        ),
        migrations.AddField(
            model_name='suppressionbaseline',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='scanner.scanjob'),
        ),
        migrations.AddField(
            model_name='suppressionbaseline',
            name='suppressed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
