# Generated by Django 5.2.12 on 2026-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_findingcategory_scanreport_solidityversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('upload', 'Uploaded File')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='syntax_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='uploaded_file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='uploaded_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]