# Generated by Django 5.2.12 on 2026-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanjob_file_metadata_and_syntax_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='Full risk breakdown from RiskScorer'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Aggregate risk score 0-100'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='risk_verdict',
            field=models.CharField(blank=True, help_text='CRITICAL/HIGH/MEDIUM/LOW/MINIMAL RISK', max_length=30),
        ),
    ]
