# Generated by Django 5.2.12 on 2026-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_scanjob_risk_assessment_scanjob_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='contract_address',
            field=models.CharField(blank=True, db_index=True, help_text='Optional 0x-prefixed Ethereum address for on-chain intelligence', max_length=42),
        ),
    ]
