# Generated by Django 5.2.12 on 2026-08-13 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanjob_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('contract_name', models.CharField(max_length=255)),
                ('source_code', models.TextField()),
                ('compiler_version', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='Solidity', max_length=50)),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scanner_v2_scan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='scan_v2_status_created_idx'), models.Index(fields=['source_hash', '-created_at'], name='scan_v2_source_hash_idx')],
            },
        ),
        migrations.CreateModel(
            name='FindingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], db_index=True, max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very_low', 'Very Low')], db_index=True, max_length=20)),
                ('analyzer', models.CharField(choices=[('slither', 'Slither'), ('mythril', 'Mythril'), ('echidna', 'Echidna'), ('heuristic', 'Heuristic'), ('manual', 'Manual')], db_index=True, max_length=30)),
                ('fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('filename', models.CharField(max_length=500)),
                ('line', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField(blank=True, null=True)),
                ('end_line', models.PositiveIntegerField(blank=True, null=True)),
                ('end_column', models.PositiveIntegerField(blank=True, null=True)),
                ('cwe_id', models.CharField(blank=True, max_length=50, null=True)),
                ('swc_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('owasp_category', models.CharField(blank=True, max_length=100, null=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=30)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scanrecord')),
            ],
            options={
                'db_table': 'scanner_v2_finding',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scan', '-severity'], name='finding_v2_scan_severity_idx'), models.Index(fields=['scan', '-created_at'], name='finding_v2_scan_created_idx'), models.Index(fields=['analyzer', '-created_at'], name='fndg_v2_analyzer_created_idx')],
            },
        ),
    ]
