# Generated by Django 5.2.12 on 2026-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_scanrecord_findingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingrecord',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='findingrecord',
            constraint=models.UniqueConstraint(fields=('scan', 'fingerprint'), name='finding_v2_scan_fp_unique'),
        ),
    ]
